-- 각 정보별로 저장될 테이블 생성 --

-- 회원 테이블
CREATE TABLE STUDY_MEMBER(
    MEMBER_ID NUMBER PRIMARY KEY,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PWD VARCHAR2(100) NOT NULL,
    NICKNAME VARCHAR2(100) NOT NULL UNIQUE,
    REG_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
-- 회원 테이블 ID 시퀸스 
CREATE SEQUENCE SEQ_STUDY_MEMBER START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_STUDY_MEMBER_ID
BEFORE INSERT ON STUDY_MEMBER FOR EACH ROW
BEGIN
    IF :NEW.MEMBER_ID IS NULL THEN
    SELECT SEQ_STUDY_MEMBER.NEXTVAL INTO :NEW.MEMBER_ID FROM DUAL;
    END IF;
END;
/
SELECT sequence_name FROM user_sequences WHERE sequence_name = 'SEQ_STUDY_MEMBER';

SELECT * FROM STUDY_MEMBER;

-- 테스트용 자료 추가
INSERT INTO STUDY_MEMBER (MEMBER_ID, EMAIL, PWD, NICKNAME) VALUES(SEQ_STUDY_MEMBER.nextval, 'A1234', 'A12345', 'TESTA1');
INSERT INTO STUDY_MEMBER (MEMBER_ID, EMAIL, PWD, NICKNAME) VALUES(SEQ_STUDY_MEMBER.nextval, 'B1234', 'A12345', 'TESTB1');
INSERT INTO STUDY_MEMBER (MEMBER_ID, EMAIL, PWD, NICKNAME) VALUES(SEQ_STUDY_MEMBER.nextval, 'C1234', 'A12345', 'TESTC1');
INSERT INTO STUDY_MEMBER (MEMBER_ID, EMAIL, PWD, NICKNAME) VALUES(SEQ_STUDY_MEMBER.nextval, 'D1234', 'A12345', 'TESTD1');
INSERT INTO STUDY_MEMBER (MEMBER_ID, EMAIL, PWD, NICKNAME) VALUES(SEQ_STUDY_MEMBER.nextval, 'E1234', 'A12345', 'TESTE1');
INSERT INTO STUDY_MEMBER (MEMBER_ID, EMAIL, PWD, NICKNAME) VALUES(SEQ_STUDY_MEMBER.nextval, 'F1234', 'A12345', 'TESTF1');
INSERT INTO STUDY_MEMBER (MEMBER_ID, EMAIL, PWD, NICKNAME) VALUES(SEQ_STUDY_MEMBER.nextval, 'G1234', 'A12345', 'TESTG1');
INSERT INTO STUDY_MEMBER (MEMBER_ID, EMAIL, PWD, NICKNAME) VALUES(SEQ_STUDY_MEMBER.nextval, 'H1234', 'A12345', 'TESTH1');
INSERT INTO STUDY_MEMBER (MEMBER_ID, EMAIL, PWD, NICKNAME) VALUES(SEQ_STUDY_MEMBER.nextval, 'I1234', 'A12345', 'TESTI1');





commit;

SELECT * FROM STUDY_MEMBER WHERE NICKNAME = 'TESTA1';
SELECT * FROM STUDY_MEMBER ORDER BY ID DESC;
SELECT * FROM STUDY_MEMBER WHERE EMAIL= 'a2@test.com';



-- 게시판 테이블
CREATE TABLE STUDY_BOARD(
    BOARD_ID NUMBER PRIMARY KEY,
    BOARD_TYPE VARCHAR2(20),
    MEMBER_ID NUMBER REFERENCES STUDY_MEMBER(MEMBER_ID),
    TITLE VARCHAR2(200) NOT NULL,
    CONTENTS CLOB NOT NULL,
    VIEW_COUNT NUMBER DEFAULT 0 NOT NULL,
    REG_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- 게시판 ID 시퀸스
CREATE SEQUENCE SEQ_STUDY_BOARD START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_STUDY_BOARD_ID
BEFORE INSERT ON STUDY_BOARD FOR EACH ROW
BEGIN
    IF :NEW.BOARD_ID IS NULL THEN
    SELECT SEQ_STUDY_BOARD.NEXTVAL INTO :NEW.BOARD_ID FROM DUAL;
    END IF;
END;
/

SELECT * FROM STUDY_BOARD;

-- 테스트용 게시글 입력  
INSERT INTO STUDY_BOARD (BOARD_ID, BOARD_TYPE, MEMBER_ID, TITLE, CONTENTS) VALUES(SEQ_STUDY_BOARD.nextval, 'TEST', 1, 'TEST_TITLE', 'TESTCONTENTS');
INSERT INTO STUDY_BOARD (BOARD_ID, BOARD_TYPE, MEMBER_ID, TITLE, CONTENTS) VALUES(SEQ_STUDY_BOARD.nextval, 'TEST2', 2, 'TEST_TITLE2', 'TESTCONTENTS');
INSERT INTO STUDY_BOARD (BOARD_ID, BOARD_TYPE, MEMBER_ID, TITLE, CONTENTS) VALUES(SEQ_STUDY_BOARD.nextval, 'TEST3', 3, 'TEST_TITLE3', 'TESTCONTENTS');
INSERT INTO STUDY_BOARD (BOARD_ID, BOARD_TYPE, MEMBER_ID, TITLE, CONTENTS) VALUES(SEQ_STUDY_BOARD.nextval, 'TEST4', 4, 'TEST_TITLE4', 'TESTCONTENTS');
INSERT INTO STUDY_BOARD (BOARD_ID, BOARD_TYPE, MEMBER_ID, TITLE, CONTENTS) VALUES(SEQ_STUDY_BOARD.nextval, 'TEST5', 5, 'TEST_TITLE5', 'TESTCONTENTS');
INSERT INTO STUDY_BOARD (BOARD_ID, BOARD_TYPE, MEMBER_ID, TITLE, CONTENTS) VALUES(SEQ_STUDY_BOARD.nextval, 'TEST6', 6, 'TEST_TITLE6', 'TESTCONTENTS');
INSERT INTO STUDY_BOARD (BOARD_ID, BOARD_TYPE, MEMBER_ID, TITLE, CONTENTS) VALUES(SEQ_STUDY_BOARD.nextval, 'TEST7', 7, 'TEST_TITLE7', 'TESTCONTENTS');
INSERT INTO STUDY_BOARD (BOARD_ID, BOARD_TYPE, MEMBER_ID, TITLE, CONTENTS) VALUES(SEQ_STUDY_BOARD.nextval, 'TEST8', 8, 'TEST_TITLE8', 'TESTCONTENTS');
INSERT INTO STUDY_BOARD (BOARD_ID, BOARD_TYPE, MEMBER_ID, TITLE, CONTENTS) VALUES(SEQ_STUDY_BOARD.nextval, 'TEST9', 9, 'TEST_TITLE9', 'TESTCONTENTS');
INSERT INTO STUDY_BOARD (BOARD_ID, BOARD_TYPE, MEMBER_ID, TITLE, CONTENTS) VALUES(SEQ_STUDY_BOARD.nextval, 'TEST0', 1, 'TEST_TITLE0', 'TESTCONTENTS');


-- 코멘트 테이블
CREATE TABLE STUDY_COMMENT(
    COMMENT_ID NUMBER PRIMARY KEY,
    BOARD_ID NUMBER NOT NULL REFERENCES STUDY_BOARD(BOARD_ID),
    MEMBER_ID NUMBER NOT NULL REFERENCES STUDY_MEMBER(MEMBER_ID),
    CONTENTS CLOB NOT NULL,
    REG_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- 코멘트 ID 시퀸스
CREATE SEQUENCE SEQ_STUDY_COMMENT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_COMMENT__ID
BEFORE INSERT ON STUDY_COMMENT FOR EACH ROW
BEGIN
    IF :NEW.COMMENT_ID IS NULL THEN
    SELECT SEQ_STUDY_COMMENT.NEXTVAL INTO :NEW.COMMENT_ID FROM DUAL;
    END IF;
END;
/

SELECT * FROM STUDY_COMMENT;

INSERT INTO STUDY_COMMENT (COMMENT_ID, BOARD_ID, MEMBER_ID, CONTENTS) VALUES(SEQ_STUDY_COMMENT.nextval, 1, 1, 'COMMENT TEST');
INSERT INTO STUDY_COMMENT (COMMENT_ID, BOARD_ID, MEMBER_ID, CONTENTS) VALUES(SEQ_STUDY_COMMENT.nextval, 2, 2, 'COMMENT TEST1');
INSERT INTO STUDY_COMMENT (COMMENT_ID, BOARD_ID, MEMBER_ID, CONTENTS) VALUES(SEQ_STUDY_COMMENT.nextval, 3, 3, 'COMMENT TEST2');
INSERT INTO STUDY_COMMENT (COMMENT_ID, BOARD_ID, MEMBER_ID, CONTENTS) VALUES(SEQ_STUDY_COMMENT.nextval, 4, 4, 'COMMENT TEST3');
INSERT INTO STUDY_COMMENT (COMMENT_ID, BOARD_ID, MEMBER_ID, CONTENTS) VALUES(SEQ_STUDY_COMMENT.nextval, 5, 5, 'COMMENT TEST4');
INSERT INTO STUDY_COMMENT (COMMENT_ID, BOARD_ID, MEMBER_ID, CONTENTS) VALUES(SEQ_STUDY_COMMENT.nextval, 6, 6, 'COMMENT TEST5');
INSERT INTO STUDY_COMMENT (COMMENT_ID, BOARD_ID, MEMBER_ID, CONTENTS) VALUES(SEQ_STUDY_COMMENT.nextval, 7, 7, 'COMMENT TEST6');
INSERT INTO STUDY_COMMENT (COMMENT_ID, BOARD_ID, MEMBER_ID, CONTENTS) VALUES(SEQ_STUDY_COMMENT.nextval, 8, 8, 'COMMENT TEST7');
INSERT INTO STUDY_COMMENT (COMMENT_ID, BOARD_ID, MEMBER_ID, CONTENTS) VALUES(SEQ_STUDY_COMMENT.nextval, 9, 9, 'COMMENT TEST8');




-- 공감/신고 테이블
CREATE TABLE REACTION (
    REACTION_ID NUMBER PRIMARY KEY,
    MEMBER_ID NUMBER NOT NULL REFERENCES STUDY_MEMBER(MEMBER_ID),
    TARGET_TYPE VARCHAR2(50),
    TARGET_ID NUMBER,
    ACTION VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_REACTION_TARGET_TYPE CHECK (UPPER(TARGET_TYPE) IN ('BOARD', 'COMMENT')),
    CONSTRAINT CK_REACTION_ACTION CHECK (UPPER(ACTION) IN ('LIKE', 'REPORT')),
    CONSTRAINT UK_REACTION_UNIQUE UNIQUE (MEMBER_ID, TARGET_TYPE, TARGET_ID, ACTION)
);

-- REACTION_ID 시퀸스
CREATE SEQUENCE SEQ_STUDY_REACTION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_STUDY_REACITON_ID
BEFORE INSERT ON REACTION FOR EACH ROW
BEGIN
    IF :NEW.REACTION_ID IS NULL THEN
    SELECT SEQ_STUDY_REACTION.NEXTVAL INTO :NEW.REACTION_ID FROM DUAL;
    END IF;
END;
/

SELECT * FROM REACTION;
INSERT INTO REACTION (REACTION_ID, MEMBER_ID, TARGET_TYPE, TARGET_ID, ACTION) VALUES(SEQ_STUDY_REACTION.nextval, 1, 'BOARD', 2, 'LIKE');
INSERT INTO REACTION (REACTION_ID, MEMBER_ID, TARGET_TYPE, TARGET_ID, ACTION) VALUES(SEQ_STUDY_REACTION.nextval, 2, 'COMMENT', 3, 'LIKE');
INSERT INTO REACTION (REACTION_ID, MEMBER_ID, TARGET_TYPE, TARGET_ID, ACTION) VALUES(SEQ_STUDY_REACTION.nextval, 3, 'BOARD', 4, 'LIKE');
INSERT INTO REACTION (REACTION_ID, MEMBER_ID, TARGET_TYPE, TARGET_ID, ACTION) VALUES(SEQ_STUDY_REACTION.nextval, 4, 'COMMENT', 5, 'LIKE');
INSERT INTO REACTION (REACTION_ID, MEMBER_ID, TARGET_TYPE, TARGET_ID, ACTION) VALUES(SEQ_STUDY_REACTION.nextval, 5, 'BOARD', 6, 'LIKE');
INSERT INTO REACTION (REACTION_ID, MEMBER_ID, TARGET_TYPE, TARGET_ID, ACTION) VALUES(SEQ_STUDY_REACTION.nextval, 6, 'COMMENT', 3, 'LIKE');
INSERT INTO REACTION (REACTION_ID, MEMBER_ID, TARGET_TYPE, TARGET_ID, ACTION) VALUES(SEQ_STUDY_REACTION.nextval, 7, 'BOARD', 5, 'REPORT');
INSERT INTO REACTION (REACTION_ID, MEMBER_ID, TARGET_TYPE, TARGET_ID, ACTION) VALUES(SEQ_STUDY_REACTION.nextval, 8, 'BOARD', 4, 'REPORT');
INSERT INTO REACTION (REACTION_ID, MEMBER_ID, TARGET_TYPE, TARGET_ID, ACTION) VALUES(SEQ_STUDY_REACTION.nextval, 9, 'COMMENT', 6, 'REPORT');
INSERT INTO REACTION (REACTION_ID, MEMBER_ID, TARGET_TYPE, TARGET_ID, ACTION) VALUES(SEQ_STUDY_REACTION.nextval, 1, 'COMMENT', 7, 'REPORT');

COMMIT;








SELECT 
    b.BOARD_ID,
    b.MEMBER_ID,
    m.NICKNAME,
    b.TITLE,
    b.VIEW_COUNT,
    NVL(SUM(CASE WHEN r.ACTION = 'LIKE' THEN 1 ELSE 0 END), 0) AS LIKE_COUNT,
    NVL(SUM(CASE WHEN r.ACTION = 'REPORT' THEN 1 ELSE 0 END), 0) AS REPORT_COUNT,
    b.REG_DATE
FROM STUDY_BOARD b
JOIN STUDY_MEMBER m ON b.MEMBER_ID = m.MEMBER_ID
LEFT JOIN REACTION r ON r.TARGET_TYPE = 'BOARD' AND r.TARGET_ID = b.BOARD_ID
WHERE b.BOARD_TYPE = 'TEST'
GROUP BY 
    b.BOARD_ID, b.MEMBER_ID, m.NICKNAME, b.TITLE, b.VIEW_COUNT, b.REG_DATE
ORDER BY b.REG_DATE DESC;





-- 게시판별 리스트
SELECT 
    b.BOARD_ID,
    b.MEMBER_ID,
    m.NICKNAME,
    b.TITLE,
    b.CONTENTS,
    b.VIEW_COUNT,
    NVL(SUM(CASE WHEN r.ACTION = 'LIKE' THEN 1 ELSE 0 END), 0) AS LIKE_COUNT,
    NVL(SUM(CASE WHEN r.ACTION = 'REPORT' THEN 1 ELSE 0 END), 0) AS REPORT_COUNT,
    b.REG_DATE
FROM STUDY_BOARD b
JOIN STUDY_MEMBER m 
    ON b.MEMBER_ID = m.MEMBER_ID
LEFT JOIN REACTION r 
    ON r.TARGET_TYPE = 'BOARD' 
   AND r.TARGET_ID = b.BOARD_ID
WHERE b.BOARD_ID = 5
GROUP BY 
    b.BOARD_ID, b.MEMBER_ID, m.NICKNAME, b.TITLE, b.CONTENTS, b.VIEW_COUNT, b.REG_DATE;



-- 게시글 상세 조회할 때 구문
SELECT t.*, b.CONTENTS
    FROM (
        SELECT 
            b.BOARD_ID,
            b.MEMBER_ID,
            m.NICKNAME,
            b.TITLE,
            b.VIEW_COUNT,
            NVL(SUM(CASE WHEN r.ACTION = 'LIKE' THEN 1 ELSE 0 END),0) AS LIKE_COUNT,
            NVL(SUM(CASE WHEN r.ACTION = 'REPORT' THEN 1 ELSE 0 END),0) AS REPORT_COUNT,
            b.REG_DATE
        FROM STUDY_BOARD b
        JOIN STUDY_MEMBER m ON b.MEMBER_ID = m.MEMBER_ID
        LEFT JOIN REACTION r 
            ON r.TARGET_TYPE='BOARD' AND r.TARGET_ID=b.BOARD_ID
        WHERE b.BOARD_ID = 2
        GROUP BY b.BOARD_ID, b.MEMBER_ID, m.NICKNAME, b.TITLE, b.VIEW_COUNT, b.REG_DATE
    ) t
    JOIN STUDY_BOARD b ON b.BOARD_ID = t.BOARD_ID;        

    commit;

SELECT t.*, b.CONTENTS
FROM (
    SELECT
        b.BOARD_ID,
        b.MEMBER_ID,
        m.NICKNAME,
        b.TITLE,
        b.VIEW_COUNT,
        NVL(SUM(CASE WHEN r.ACTION = 'LIKE' THEN 1 ELSE 0 END),0) AS LIKE_COUNT,
        NVL(SUM(CASE WHEN r.ACTION = 'REPORT' THEN 1 ELSE 0 END),0) AS REPORT_COUNT,
        b.REG_DATE
    FROM STUDY_BOARD b
    JOIN STUDY_MEMBER m ON b.MEMBER_ID = m.MEMBER_ID
    LEFT JOIN REACTION r
        ON r.TARGET_TYPE='BOARD' AND r.TARGET_ID=b.BOARD_ID
    WHERE b.BOARD_ID = 3
    GROUP BY b.BOARD_ID, b.MEMBER_ID, m.NICKNAME, b.TITLE, b.VIEW_COUNT, b.REG_DATE
) t
JOIN STUDY_BOARD b ON b.BOARD_ID = t.BOARD_ID

SELECT t.*, b.CONTENTS
        FROM (
            SELECT
                b.BOARD_ID,
                b.MEMBER_ID,
                m.NICKNAME,
                b.TITLE,
                b.VIEW_COUNT,
                NVL(SUM(CASE WHEN r.ACTION = 'LIKE' THEN 1 ELSE 0 END),0) AS LIKE_COUNT,
                NVL(SUM(CASE WHEN r.ACTION = 'REPORT' THEN 1 ELSE 0 END),0) AS REPORT_COUNT,
                b.REG_DATE
            FROM STUDY_BOARD b
            JOIN STUDY_MEMBER m ON b.MEMBER_ID = m.MEMBER_ID
            LEFT JOIN REACTION r
                ON r.TARGET_TYPE='BOARD' AND r.TARGET_ID=b.BOARD_ID
            WHERE b.BOARD_ID = 3
            GROUP BY b.BOARD_ID, b.MEMBER_ID, m.NICKNAME, b.TITLE, b.VIEW_COUNT, b.REG_DATE
        ) t
        JOIN STUDY_BOARD b ON b.BOARD_ID = t.BOARD_ID;

 SELECT 
    t.BOARD_ID       AS BOARD_ID,
    t.MEMBER_ID      AS MEMBER_ID,
    t.NICKNAME       AS NICKNAME,
    t.TITLE          AS TITLE,
    t.VIEW_COUNT     AS VIEW_COUNT,
    t.LIKE_COUNT     AS LIKE_COUNT,
    t.REPORT_COUNT   AS REPORT_COUNT,
    t.REG_DATE       AS REG_DATE,
    b.CONTENTS       AS CONTENTS
FROM (
    SELECT
        b.BOARD_ID,
        b.MEMBER_ID,
        m.NICKNAME,
        b.TITLE,
        b.VIEW_COUNT,
        NVL(SUM(CASE WHEN r.ACTION = 'LIKE' THEN 1 ELSE 0 END), 0) AS LIKE_COUNT,
        NVL(SUM(CASE WHEN r.ACTION = 'REPORT' THEN 1 ELSE 0 END), 0) AS REPORT_COUNT,
        b.REG_DATE
    FROM STUDY_BOARD b
    JOIN STUDY_MEMBER m ON b.MEMBER_ID = m.MEMBER_ID
    LEFT JOIN REACTION r
        ON r.TARGET_TYPE='BOARD' AND r.TARGET_ID=b.BOARD_ID
    WHERE b.BOARD_ID = 3
    GROUP BY b.BOARD_ID, b.MEMBER_ID, m.NICKNAME, b.TITLE, b.VIEW_COUNT, b.REG_DATE
) t
JOIN STUDY_BOARD b ON b.BOARD_ID = t.BOARD_ID;

-- 공감순위별 조회
SELECT * FROM (
            SELECT 
                b.BOARD_ID,
                b.BOARD_TYPE,
                m.NICKNAME,
                b.TITLE,
                NVL(SUM(CASE WHEN r.ACTION = 'LIKE' THEN 1 ELSE 0 END), 0) AS LIKE_COUNT,
                b.VIEW_COUNT,
                TO_CHAR(b.REG_DATE, 'YYYY-MM-DD HH24:MI') AS REG_DATE
            FROM STUDY_BOARD b
            JOIN STUDY_MEMBER m ON b.MEMBER_ID = m.MEMBER_ID
            LEFT JOIN REACTION r ON r.TARGET_TYPE='BOARD' AND r.TARGET_ID=b.BOARD_ID
            GROUP BY b.BOARD_ID, b.BOARD_TYPE, m.NICKNAME, b.TITLE, b.VIEW_COUNT, b.REG_DATE
            ORDER BY LIKE_COUNT DESC
        )
        WHERE ROWNUM <= 10

