-- 각 정보별로 저장될 테이블 생성 --

-- 회원 테이블
CREATE TABLE STUDY_MEMBER(
    MEMBER_ID NUMBER PRIMARY KEY,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PWD VARCHAR2(100) NOT NULL,
    NICKNAME VARCHAR2(100) NOT NULL UNIQUE,
    REG_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
-- 회원 테이블 ID 시퀸스 
CREATE SEQUENCE SEQ_STUDY_MEMBER START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_STUDY_MEMBER_ID
BEFORE INSERT ON STUDY_MEMBER FOR EACH ROW
BEGIN
    IF :NEW.MEMBER_ID IS NULL THEN
    SELECT SEQ_STUDY_MEMBER.NEXTVAL INTO :NEW.MEMBER_ID FROM DUAL;
    END IF;
END;
/
SELECT sequence_name FROM user_sequences WHERE sequence_name = 'SEQ_STUDY_MEMBER';

SELECT * FROM STUDY_MEMBER;

INSERT INTO STUDY_MEMBER (MEMBER_ID, EMAIL, PWD, NICKNAME) VALUES(SEQ_STUDY_MEMBER.nextval, 'A1234', 'A12345', 'TESTA1');

commit;

SELECT * FROM STUDY_MEMBER WHERE NICKNAME = 'TESTA1';
SELECT * FROM STUDY_MEMBER ORDER BY ID DESC;
SELECT * FROM STUDY_MEMBER WHERE EMAIL= 'a2@test.com';



-- 게시판 테이블
CREATE TABLE STUDY_BOARD(
    BOARD_ID NUMBER PRIMARY KEY,
    BOARD_TYPE VARCHAR2(20),
    MEMBER_ID NUMBER REFERENCES STUDY_MEMBER(MEMBER_ID),
    TITLE VARCHAR2(200) NOT NULL,
    CONTENTS CLOB NOT NULL,
    VIEW_COUNT NUMBER DEFAULT 0 NOT NULL,
    REG_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- 게시판 ID 시퀸스
CREATE SEQUENCE SEQ_STUDY_BOARD START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_STUDY_BOARD_ID
BEFORE INSERT ON STUDY_BOARD FOR EACH ROW
BEGIN
    IF :NEW.BOARD_ID IS NULL THEN
    SELECT SEQ_STUDY_BOARD.NEXTVAL INTO :NEW.BOARD_ID FROM DUAL;
    END IF;
END;
/

SELECT * FROM STUDY_BOARD;

INSERT INTO STUDY_BOARD (BOARD_ID, BOARD_TYPE, MEMBER_ID, TITLE, CONTENTS) VALUES(SEQ_STUDY_BOARD.nextval, 'TEST', 1, 'TEST_TITLE', 'TESTCONTENTS');


-- 코멘트 테이블
CREATE TABLE STUDY_COMMENT(
    COMMENT_ID NUMBER PRIMARY KEY,
    BOARD_ID NUMBER NOT NULL REFERENCES STUDY_BOARD(BOARD_ID),
    MEMBER_ID NUMBER NOT NULL REFERENCES STUDY_MEMBER(MEMBER_ID),
    CONTENTS CLOB NOT NULL,
    REG_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- 코멘트 ID 시퀸스
CREATE SEQUENCE SEQ_STUDY_COMMENT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_COMMENT__ID
BEFORE INSERT ON STUDY_COMMENT FOR EACH ROW
BEGIN
    IF :NEW.COMMENT_ID IS NULL THEN
    SELECT SEQ_STUDY_COMMENT.NEXTVAL INTO :NEW.COMMENT_ID FROM DUAL;
    END IF;
END;
/

SELECT * FROM STUDY_COMMENT;

INSERT INTO STUDY_COMMENT (COMMENT_ID, BOARD_ID, MEMBER_ID, CONTENTS) VALUES(SEQ_STUDY_COMMENT.nextval, 1, 1, 'COMMENT TEST');




-- 공감/신고 테이블
CREATE TABLE REACTION (
    REACTION_ID NUMBER PRIMARY KEY,
    MEMBER_ID NUMBER NOT NULL REFERENCES STUDY_MEMBER(MEMBER_ID),
    TARGET_TYPE VARCHAR2(50),
    TARGET_ID NUMBER,
    ACTION VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_REACTION_TARGET_TYPE CHECK (TARGET_TYPE IN ('BOARD', 'COMMENT')),
    CONSTRAINT CK_REACTION_ACTION CHECK (ACTION IN ('LIKE', 'REPORT')),
    CONSTRAINT UK_REACTION_UNIQUE UNIQUE (MEMBER_ID, TARGET_TYPE, TARGET_ID, ACTION)
);

-- REACTION_ID 시퀸스
CREATE SEQUENCE SEQ_STUDY_REACTION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_STUDY_REACITON_ID
BEFORE INSERT ON REACTION FOR EACH ROW
BEGIN
    IF :NEW.REACTION_ID IS NULL THEN
    SELECT SEQ_STUDY_REACTION.NEXTVAL INTO :NEW.REACTION_ID FROM DUAL;
    END IF;
END;
/

SELECT * FROM REACTION;
INSERT INTO REACTION (REACTION_ID, MEMBER_ID, TARGET_TYPE, TARGET_ID, ACTION) VALUES(SEQ_STUDY_REACTION.nextval, 1, 'BOARD', 2, 'LIKE');
INSERT INTO REACTION (REACTION_ID, MEMBER_ID, TARGET_TYPE, TARGET_ID, ACTION) VALUES(SEQ_STUDY_REACTION.nextval, 1, 'COMMENT', 1, 'LIKE');

COMMIT;